### PR TITLE
adding LSP_Lines

### PR DESCRIPTION
**Pull request by luxus**
instead of having virtual text behind the line, see https://git.sr.ht/~whynothugo/lsp_lines.nvim

dunno if you are interested. if not, just close it :D

### CODE REVIEW

**Review by abzcoding — APPROVED** [review]

**Comment by Uzaaft** [comment]
Damn that looks sexy. 😮

**Comment by luxus** [comment]
Ah i didn't add the key mapping to toggle it. Maybe that makes sense

**Comment by Uzaaft** [comment]
Should figure out what makes most sense.
IMHO, a Key mapping like `<leader>D l` makes sense. What do you think @luxus? D for Display, and then l for lsp_lines

**Comment by luxus** [comment]
@Uzaaft do u mean `<leader>d l` ? there is no `<leader>D`
I will add d l if @abzcoding is cool with it

**Comment by abzcoding** [comment]
> @Uzaaft do u mean `<leader>d l` ? there is no `<leader>D`
> I will add d l if @abzcoding is cool with it

sure why not

**Comment by Uzaaft** [comment]
Does it make sense to have it under the debug section? Perhaps `<leader>v l`?

**Pull request merged**
